title: Knowledge DB
description: Experienced gathered in tech
theme: just-the-docs

url: https://pgmarc.github.io

callouts:
  warning:
    color: red
  note:
    color: purple
  highlight:
    color: yellow
  important:
    color: blue
